# Copyright 2026 Hewlett Packard Enterprise Development LP.
# SPDX-License-Identifier: MIT
#
# Kernel modules required for configfs-tsm (TEE attestation)
# https://www.kernel.org/doc/Documentation/ABI/testing/configfs-tsm
configfs
tsm
tsm_report
sev-guest
tdx-guest
